# Generated by Django 4.2.3 on 2023-09-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('ratings', models.PositiveIntegerField()),
                ('ratingsCount', models.PositiveIntegerField()),
                ('img', models.URLField()),
                ('shipping', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
